@startuml
left to right direction
skinparam packageStyle rectangle
actor Utilisateur
database Database
rectangle "Modifier son mot de passe" {
  Utilisateur -- (Modifier son mot de passe)
  (Modifier son mot de passe) -- Database
}
@enduml