name: Code quality

on: [push, pull_request]

jobs:
  phpcs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Detecting PHP Code Standards Violations
        run: vendor/bin/phpcs --standard=PSR12 tests src domain
